# -*- coding: utf-8 -*-
"""The design palette, and the CSS custom properties generated from it.

One definition feeds two consumers: this module writes assets/css/tokens.css,
and the charts fill their bars with var(--s1) and var(--ord3) rather
than with hex values, so a theme change needs no JavaScript.
"""

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                '..', 'src_data'))

import config      # noqa: E402

TOKENS_FILE = os.path.join(config.PROJECT_PATH, 'assets', 'css', 'tokens.css')

# Validated palette slots. Checked with the dataviz validator in both modes:
# categorical slots 1-3 pass all-pairs; the 5-step ordinal ramp passes with
# light-mode steps 250-650 and dark-mode steps 100-500.
LIGHT = {
    'surface': '#fcfcfb', 'page': '#f9f9f7',
    'text': '#0b0b0b', 'text2': '#52514e', 'muted': '#898781',
    'grid': '#e1e0d9', 'baseline': '#c3c2b7',
    's1': '#2a78d6', 's2': '#eb6834', 's3': '#1baf7a',
    'neutral': '#cbcac3',
    'ord': ['#86b6ef', '#5598e7', '#2a78d6', '#1c5cab', '#104281'],
}
DARK = {
    'surface': '#1a1a19', 'page': '#0d0d0d',
    'text': '#ffffff', 'text2': '#c3c2b7', 'muted': '#898781',
    'grid': '#2c2c2a', 'baseline': '#383835',
    's1': '#3987e5', 's2': '#d95926', 's3': '#199e70',
    'neutral': '#4f4f4b',
    'ord': ['#cde2fb', '#9ec5f4', '#6da7ec', '#3987e5', '#256abf'],
}

# Status colours used by the action plan's CSS only, so they are kept out of
# LIGHT/DARK: those two are serialised into the page for the chart JS, which
# has no use for them. Same value in both modes, contrast-checked on both.
STATUS = {'good': '#0ca30c', 'critical': '#d03b3b'}


def tokens_css():
    """Render the design tokens from LIGHT/DARK into a standalone stylesheet.

    The palettes below feed both the chart JS and the page CSS, so the token
    sheet is generated rather than hand-kept in sync.
    """

    def block(palette, indent, border, shadow, wash, scheme):
        pad = ' ' * indent
        return (
            f"{pad}--surface: {palette['surface']}; --page: {palette['page']};\n"
            f"{pad}--text: {palette['text']}; --text2: {palette['text2']};"
            f" --muted: {palette['muted']};\n"
            f"{pad}--grid: {palette['grid']}; --baseline: {palette['baseline']};\n"
            f"{pad}--s1: {palette['s1']}; --s2: {palette['s2']};"
            f" --s3: {palette['s3']};\n"
            f"{pad}--good: {STATUS['good']}; --critical: {STATUS['critical']};\n"
            # The chart colours became CSS too once the charts moved to
            # pre-rendered SVG: filling a bar with var(--ord3) keeps it
            # theme-reactive with no JavaScript re-drawing it on a theme flip.
            f"{pad}--neutral: {palette['neutral']};\n"
            + ''.join(f"{pad}--ord{i + 1}: {step};\n"
                      for i, step in enumerate(palette['ord']))
            + f"{pad}--border: {border}; --shadow: {shadow};\n"
            f"{pad}--wash: {wash};\n"
            f"{pad}color-scheme: {scheme};\n")

    light = block(LIGHT, 2, 'rgba(11,11,11,0.10)',
                  '0 1px 2px rgba(11,11,11,0.04)', 'rgba(11,11,11,0.035)', 'light')
    dark_nested = block(DARK, 4, 'rgba(255,255,255,0.10)', 'none',
                        'rgba(255,255,255,0.05)', 'dark')
    dark_flat = block(DARK, 2, 'rgba(255,255,255,0.10)', 'none',
                      'rgba(255,255,255,0.05)', 'dark')
    return (
        '/* tokens.css - generated by src_viz/tokens.py from its\n'
        '   LIGHT/DARK palettes. Do not edit by hand; edit the palettes. */\n'
        ':root {\n' + light + '}\n'
        '@media (prefers-color-scheme: dark) {\n'
        '  :root:not([data-theme="light"]) {\n' + dark_nested + '  }\n'
        '}\n'
        ':root[data-theme="dark"] {\n' + dark_flat + '}\n')
